name: mkt-monitor 镜像构建发布 CI


on:

  workflow_dispatch:


permissions:

  contents: read



env:

  HARBOR_REGISTRY: host.docker.internal:8088

  IMAGE_REPOSITORY: library/mkt-monitor



jobs:


  build:


    name: 构建并上传 Harbor 镜像


    runs-on: arc-mkt-monitor



    steps:



      # ==========================
      # 拉取代码
      # ==========================

      - name: 拉取代码

        uses: actions/checkout@v4



      # ==========================
      # 环境检查
      # ==========================

      - name: 初始化环境

        run: |

          echo "========== Runner =========="

          uname -a


          echo

          echo "========== Docker =========="

          docker version



      # ==========================
      # 生成镜像版本
      #
      # 格式:
      # 20260929-a1b2c3d
      #
      # ==========================

      - name: 设置镜像版本

        run: |

          DATE=$(date +%Y%m%d)

          SHA=$(git rev-parse --short HEAD)


          IMAGE_TAG=${DATE}-${SHA}


          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV


          echo "IMAGE_FULL_NAME=${HARBOR_REGISTRY}/${IMAGE_REPOSITORY}:${IMAGE_TAG}" >> $GITHUB_ENV


          echo "IMAGE_FULL_NAME=${HARBOR_REGISTRY}/${IMAGE_REPOSITORY}:${IMAGE_TAG}"



      # ==========================
      # Harbor 网络检查
      # ==========================

      - name: 检查 Harbor Registry

        run: |

          echo "Check Harbor"

          curl -I \
          http://${HARBOR_REGISTRY}/v2/ || true



      # ==========================
      # 登录 Harbor
      # ==========================

      - name: 登录 Harbor

        env:

          HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}

          HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}


        run: |


          if [ -z "$HARBOR_USERNAME" ]; then

            echo "HARBOR_USERNAME missing"

            exit 1

          fi



          if [ -z "$HARBOR_PASSWORD" ]; then

            echo "HARBOR_PASSWORD missing"

            exit 1

          fi



          echo "$HARBOR_PASSWORD" | \

          docker login \

          ${HARBOR_REGISTRY} \

          --username "$HARBOR_USERNAME" \

          --password-stdin



      # ==========================
      # Build
      # ==========================

      - name: 构建 Docker 镜像

        run: |


          docker build \

          -t ${IMAGE_FULL_NAME} \

          .



      # ==========================
      # Push
      # ==========================

      - name: 上传 Harbor


        run: |


          docker push ${IMAGE_FULL_NAME}



      # ==========================
      # 验证
      # ==========================

      - name: 查看镜像


        run: |


          echo "========== Local Images =========="


          docker images


          echo

          echo "========== Build Image =========="


          echo ${IMAGE_FULL_NAME}