name: mkt-monitor 镜像构建发布 CI


on:

  workflow_dispatch:



permissions:

  contents: read



env:

  # Harbor 地址
  HARBOR_REGISTRY: host.docker.internal:8088

  # Harbor 用户
  HARBOR_USERNAME: admin

  # 实验环境密码
  HARBOR_PASSWORD: HarborLab-2026-ChangeMe



jobs:


  build:


    name: 构建并上传 Harbor 镜像


    runs-on: arc-mkt-monitor



    steps:


      # =====================================
      # Checkout
      # =====================================

      - name: 拉取代码

        uses: actions/checkout@v4



      # =====================================
      # 环境检查
      # =====================================

      - name: Runner 环境检查

        run: |

          echo "========== Runner =========="

          uname -a


          echo

          echo "========== Docker Version =========="

          docker version



      # =====================================
      # Harbor 网络检查
      # =====================================

      - name: Harbor 连通性检查

        run: |

          echo "========== Harbor Test =========="


          curl -v \
          http://$HARBOR_REGISTRY/v2/ || true



      # =====================================
      # 设置镜像版本
      #
      # 示例:
      #
      # host.docker.internal:8088/library/mkt-monitor:20260929-a1b2c3d
      #
      # =====================================

      - name: 设置镜像版本

        run: |

          DATE=$(date +%Y%m%d)

          SHA=$(git rev-parse --short HEAD)


          IMAGE_TAG=${DATE}-${SHA}


          echo "IMAGE_NAME=library/mkt-monitor" >> $GITHUB_ENV

          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV


          echo "=============================="

          echo "IMAGE TAG: ${IMAGE_TAG}"

          echo "=============================="



      # =====================================
      # 登录 Harbor
      #
      # 实验环境明文
      # =====================================

      - name: 登录 Harbor

        run: |


          echo "Login Harbor: $HARBOR_REGISTRY"


          docker login \
            $HARBOR_REGISTRY \
            -u $HARBOR_USERNAME \
            -p $HARBOR_PASSWORD



      # =====================================
      # Build
      # =====================================

      - name: 构建 Docker 镜像

        run: |


          docker build \

            -t $HARBOR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG \

            .



      # =====================================
      # 查看本地镜像
      # =====================================

      - name: 查看镜像

        run: |


          docker images

      - name: Docker Registry Check
        run: |
          
          docker info | grep -A10 "Insecure Registries"

      # =====================================
      # Push Harbor
      # =====================================

      - name: 上传 Harbor

        run: |


          docker push \

          $HARBOR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG



      # =====================================
      # 验证
      # =====================================

      - name: 完成检查

        run: |


          echo "================================"

          echo "Harbor Image Uploaded"

          echo "$HARBOR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG"

          echo "================================"